files:
  include: "src/static/stylesheets/*.scss"
  ignore:
    - "src/static/stylesheets/loader.scss"
rules:
  class-name-format:
  - 2
  - convention: hyphenatedbem
  leading-zero:
  - 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  quotes:
  - 1
  - style: double
